[build] 
  publish = "www"
  command = "echo 'No build command for this site'"

[dev] 
  publish = "www"
  command = "echo 'No build command for this site'"

[functions]
  node_bundler = "esbuild"


[[redirects]]
  from = "/ask"
  to = "/.netlify/functions/ask"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/answer"
  status = 200
  force = false 
