[build] 
  publish = "dist"
  command = "npx eleventy"

[dev] 
  publish = "dist"
  command = "npx eleventy --watch"

[[redirects]]
  from = "/ask"
  to = "/.netlify/functions/ask"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/answer"
  status = 200
  force = false 
